//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otello.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class administrador
    {
        [Required(ErrorMessage = "Usuario Incorrecto, intente de nuevo")]

        public string id_admin { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password Incorrecto, intente de nuevo")]

        public string pass { get; set; }
        public string Error { get; set; }
    }
}
