//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id_detalle { get; set; }
        public string usuario1 { get; set; }
        public Nullable<int> no_fichas { get; set; }
        public Nullable<int> movimiento { get; set; }
        public Nullable<int> estado1 { get; set; }
    }
}
